### ISSUE TITLE
Support replacing waiting for feedback with feedback provided on Pull Requests

### ISSUE THREAD

**Issue by rwinch** [spring-io/issue-bot#15]
Currently the issue bot ignores pull requests all together. It would be nice if the issue bot would replace waiting for feedback with feedback provided on pull requests. However, just as it works today the bot would not close a pull request if feedback is not provided.

cc @rstoyanchev @philwebb

**Comment by wilkinsona** [comment]
Rob and I already discussed this on Slack and I am in favour. I'd like to reach agreement across all the teams using the Bot (Boot, Framework, and Security) before making the change.

**Comment by rstoyanchev** [comment]
We discussed this in the Spring Framework team, and agree with the change.

**Comment by philwebb** [comment]
+1

**Comment by wilkinsona** [comment]
Pull requests should now have their labels updated when feedback is provided. Please let me know if you see any unexpected behaviour.
