### ISSUE TITLE
JIRA Support?

### ISSUE THREAD

**Issue by rstoyanchev** [spring-io/issue-bot#4]
I'd like to use a similar bot with Jira for the Spring Framework. I'm primarily interested in the feedback listener. Less so in the triage listener since reviewing new issues by hand is straight forward and also provides a convenient opportunity for basic validations such as assigning a component (core, web, etc) to ensure accurate search/filtering of issues for triage and thereafter, checking for any obvious missing bits like version info, and so on.

What's your take on where such work should be done, here or in a separate project? From what I can see this project is likely re-usable for other Github projects, assuming they follow a similar process. However if not using `GitHubOperations` what's left is mostly a very basic loop pushing issues into issue listeners as far as I can tell and for that issue retrieval and listener implementations would have to be redone for Jira. Even core contracts like `Issue` and `Page` are in the github package at the moment. I suppose that could be restructured but abstracting Github vs Jira issues might not be so feasible. 

To me it looks more like a separate `issue-bot-jira` would make more sense but I'm interested to hear your thoughts. Related to that, if we are to have multiple issue bots, we should probably consider the best way to accommodate a potentially expanding number of "issue bot" projects (e.g. Spring Cloud with #2). For Jira too it would probably be worthwhile to split out any Spring Framework specific configuration from the start (e.g. `issue-bot-jira` vs `issue-bot-springframework`).

**Comment by wilkinsona** [comment]
> What's your take on where such work should be done, here or in a separate project? 

The code was written only with GitHub in mind, hence its current design and structure. My feeling from having worked a little bit with JIRA's API for the release calendar is that there are enough conceptual differences between GitHub issues and JIRA to justify a separate project.

> We should probably consider the best way to accommodate a potentially expanding number of "issue bot" projects (e.g. Spring Cloud with #2). For Jira too it would probably be worthwhile to split out any Spring Framework specific configuration from the start (e.g. `issue-bot-jira` vs `issue-bot-springframework`).

I believe @spencergibb is running the code in [this branch](https://github.com/wilkinsona/issue-bot/tree/multiple-repositories) that supports the monitoring of multiple repositories. It needs to be finished off and merged back into master to resolve #2.

In the interests of consistency across projects, I think we should strive for one bot for GitHub and one bot for JIRA, with each bot being configurable enough to meet each individual project's needs while also maintaining an approach that is as consistent as possible.

**Comment by rstoyanchev** [comment]
Okay, thanks. I'm going to close this since we agree any potential Jira support wouldn't be in this repo in any case.
